version: "3.1"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: servicepls-api
    container_name: api
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOST=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - TOKEN_SECRET=$TOKEN_SECRET
      - CRYPT_TOKEN=$CRYPT_TOKEN
      - API_PORT=$API_PORT
    depends_on:
      - db
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - ./api:/var/node/spapi
      - ./api/node_modules:/var/node/spapi/node_modules
    networks:
      - internal
      - web
    command: scripts/wait-for.sh db:$MONGO_PORT -- node_modules/.bin/nodemon /var/node/spapi/src/index.js

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: servicepls-app
    container_name: app
    restart: unless-stopped
    env_file: .env
    environment:
      - NUXT_HOST=$NUXT_HOST
      - NUXT_PORT=$NUXT_PORT
      - NUXT_ENV_API_BASEURL=$API_BASEURL
      - NUXT_ENV_API_PORT=$API_PORT
    depends_on:
      - api
    ports:
      - $NUXT_PORT:$NUXT_PORT
    volumes:
      - ./app:/var/node/spapp
      - ./app/node_modules:/var/node/spapp/node_modules
    networks:
      - web
    command: npm run dev

  db:
    image: mongo:4.0.20-xenial
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    ports:
      - $MONGO_PORT:$MONGO_PORT
    networks:
      - internal

networks:
  internal:
  web:

volumes:
  dbdata:
